services:
  app:
    build:
      context: ./
    volumes:
      - ./src:/app/src
      - ./docker:/app/docker
      - ./dist:/app/dist
      # - ./out:/app/out
      - ./hooks:/app/hooks
    command: "/app/docker/build_pyinstaller.sh"
